// Auto-generated by scripts/upload-to-r2.js — do not edit manually
export const MODEL_URLS: Record<string, string> = {
  "bathroom-vanity": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/bathroom-vanity.glb",
  "bed": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/bed.glb",
  "coffee-table": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/coffee-table.glb",
  "dining-chair": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/dining-chair.glb",
  "dining-table": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/dining-table.glb",
  "floor-lamp": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/floor-lamp.glb",
  "fridge": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/fridge.glb",
  "nightstand": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/nightstand.glb",
  "office-chair": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/office-chair.glb",
  "office-desk": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/office-desk.glb",
  "potted-plant": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/potted-plant.glb",
  "sofa": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/sofa.glb",
  "toilet": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/toilet.glb",
  "tv-unit": "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models/tv-unit.glb"
};

export const MODEL_CDN_BASE = process.env.R2_PUBLIC_URL
  ? `${process.env.R2_PUBLIC_URL}/models`
  : "https://pub-27d9a7371b6d47ff94fee1a3228f1720.r2.dev/models";
